#Default meerkathi pipeline configuration
schema_version: v0.1.1

#Default meerkathi pipeline configuration
schema_version: v0.1.1


mask_from_catalog:
  __helpstr: Build mask from catalog
  enable: true
  order: 9
  centre_coord: ['03:18:0.000', '-37:27:0.000']
  catalog_mask: 'sumss_mask.fits'
  fornaxa_finalmask: 'fornaxa_mask.fits'
  final_mask: 'sumss_fornaxa_mask.fits'
  query_SUMMS:
    enable: true
    width_image: '4d'
  build_beam:
    enable: true
    img_size: 8192      #must be the same as  im_npix in selfcal worker
    cell_size: 1.3         #this will change and we will use the self_cal_3GC keywords
    frequency: 1.e-9
  make_mosaic:
    enable: true
  casa_regrid:
    enable: true
  pb_correction:
    enable: true
  make_mask:
    enable: true 
    cutoff: 0.7e-3
  fornaxa_mask:
    enable: true 
    fornaxa_cutoff: 8.e-4
  add_masks:
    enable: true
